# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sort_rcpp <- function(x) {
    .Call('ModelMetrics_sort_rcpp', PACKAGE = 'ModelMetrics', x)
}

rank <- function(x) {
    .Call('ModelMetrics_rank', PACKAGE = 'ModelMetrics', x)
}

auc_ <- function(actual, predicted) {
    .Call('ModelMetrics_auc_', PACKAGE = 'ModelMetrics', actual, predicted)
}

logLoss_ <- function(actual, predicted) {
    .Call('ModelMetrics_logLoss_', PACKAGE = 'ModelMetrics', actual, predicted)
}

mlogLoss_ <- function(actual, predicted) {
    .Call('ModelMetrics_mlogLoss_', PACKAGE = 'ModelMetrics', actual, predicted)
}

plogLoss_ <- function(actual, predicted) {
    .Call('ModelMetrics_plogLoss_', PACKAGE = 'ModelMetrics', actual, predicted)
}

mse_ <- function(actual, predicted) {
    .Call('ModelMetrics_mse_', PACKAGE = 'ModelMetrics', actual, predicted)
}

rmse_ <- function(actual, predicted) {
    .Call('ModelMetrics_rmse_', PACKAGE = 'ModelMetrics', actual, predicted)
}

