# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sort_rcpp <- function(x) {
    .Call('ModelMetrics_sort_rcpp', PACKAGE = 'ModelMetrics', x)
}

rank <- function(x) {
    .Call('ModelMetrics_rank', PACKAGE = 'ModelMetrics', x)
}

auc_ <- function(actual, predicted) {
    .Call('ModelMetrics_auc_', PACKAGE = 'ModelMetrics', actual, predicted)
}

confusionMatrix_ <- function(actual, predicted, cutoff) {
    .Call('ModelMetrics_confusionMatrix_', PACKAGE = 'ModelMetrics', actual, predicted, cutoff)
}

ppv_ <- function(actual, predicted, cutoff) {
    .Call('ModelMetrics_ppv_', PACKAGE = 'ModelMetrics', actual, predicted, cutoff)
}

npv_ <- function(actual, predicted, cutoff) {
    .Call('ModelMetrics_npv_', PACKAGE = 'ModelMetrics', actual, predicted, cutoff)
}

recall_ <- function(actual, predicted, cutoff) {
    .Call('ModelMetrics_recall_', PACKAGE = 'ModelMetrics', actual, predicted, cutoff)
}

f1Score_ <- function(actual, predicted, cutoff) {
    .Call('ModelMetrics_f1Score_', PACKAGE = 'ModelMetrics', actual, predicted, cutoff)
}

mae_ <- function(actual, predicted) {
    .Call('ModelMetrics_mae_', PACKAGE = 'ModelMetrics', actual, predicted)
}

ce_ <- function(actual, predicted) {
    .Call('ModelMetrics_ce_', PACKAGE = 'ModelMetrics', actual, predicted)
}

mse_ <- function(actual, predicted) {
    .Call('ModelMetrics_mse_', PACKAGE = 'ModelMetrics', actual, predicted)
}

msle_ <- function(actual, predicted) {
    .Call('ModelMetrics_msle_', PACKAGE = 'ModelMetrics', actual, predicted)
}

rmsle_ <- function(actual, predicted) {
    .Call('ModelMetrics_rmsle_', PACKAGE = 'ModelMetrics', actual, predicted)
}

rmse_ <- function(actual, predicted) {
    .Call('ModelMetrics_rmse_', PACKAGE = 'ModelMetrics', actual, predicted)
}

logLoss_ <- function(actual, predicted) {
    .Call('ModelMetrics_logLoss_', PACKAGE = 'ModelMetrics', actual, predicted)
}

mlogLoss_ <- function(actual, predicted) {
    .Call('ModelMetrics_mlogLoss_', PACKAGE = 'ModelMetrics', actual, predicted)
}

plogLoss_ <- function(actual, predicted) {
    .Call('ModelMetrics_plogLoss_', PACKAGE = 'ModelMetrics', actual, predicted)
}

